UPDATE creature_template SET ScriptName = "" WHERE difficulty_entry_1 > 0 OR ScriptName LIKE "%boss_%";
UPDATE `access_requirement` SET `quest_done_A` = 10285, `quest_done_H` = 10285, `quest_failed_text` = 'В данный момент доступ в подземелья закрыт.';
TRUNCATE TABLE `creature_ai_scripts`;
TRUNCATE TABLE `creature_ai_texts`;
TRUNCATE TABLE `creature_onkill_reputation`;
TRUNCATE TABLE `creature_text`;
TRUNCATE TABLE `db_script_string`;
TRUNCATE TABLE `gameobject_loot_template`;
TRUNCATE TABLE `disenchant_loot_template`;
TRUNCATE TABLE `fishing_loot_template`;
TRUNCATE TABLE `pickpocketing_loot_template`;
TRUNCATE TABLE `skinning_loot_template`;
TRUNCATE TABLE `prospecting_loot_template`;
TRUNCATE TABLE `creature_loot_template`;
DELETE FROM `event_scripts` WHERE `command` IN (0, 1, 7, 8);
DELETE FROM `waypoint_scripts` WHERE `command` IN (0, 1, 7, 8);
DELETE FROM `gameobject_scripts` WHERE `command` IN (0, 1, 7, 8);
DELETE `g`, `pg` FROM `gameobject` `g` LEFT JOIN `gameobject_template` `gt` ON `g`.`id` = `gt`.`entry` 
LEFT JOIN `pool_gameobject` `pg` ON `g`.`guid` = `pg`.`guid` WHERE `gt`.`type` IN (2, 3, 25);
DELETE FROM `gameobject_template` WHERE type IN (2, 3, 25);
UPDATE `creature_template` SET  `lootid` = 0, `pickpocketloot` = 0, `skinloot` = 0;
UPDATE `creature_transport` SET `emote` = 0;
UPDATE `item_template` SET `RequiredDisenchantSkill` = -1, `DisenchantID` = 0;
UPDATE `gameobject_template` SET `questItem1` = 0, `questItem2` = 0, `questItem3` = 0, `questItem4` = 0, `questItem5` = 0, `questItem6` = 0;
UPDATE `creature_template` SET `AIName` = '' WHERE `AIName` = 'EventAI' OR `AIName` = 'SmartAI';
TRUNCATE `quest_end_scripts`;
TRUNCATE `quest_poi`;
TRUNCATE `quest_poi_points`;
TRUNCATE `quest_start_scripts`;
TRUNCATE `gameobject_questrelation`;
TRUNCATE `gameobject_involvedrelation`;
TRUNCATE `pool_quest`;
TRUNCATE `game_event_seasonal_questrelation`;
TRUNCATE `lfg_dungeon_rewards`;
TRUNCATE `areatrigger_involvedrelation`;
DELETE FROM `event_scripts` WHERE `command` = 7;
DELETE FROM `disables` WHERE `sourceType` = 1;
DELETE FROM `spell_area` WHERE `quest_start` <> 0;
DELETE FROM `spell_area` WHERE `quest_end` <> 0;
DELETE FROM `smart_scripts` WHERE `event_type` IN (19, 20);
DELETE FROM `smart_scripts` WHERE `action_type` IN (6, 7, 15, 16, 26, 33);
DELETE FROM `smart_scripts` WHERE `action_type` = 53 AND `action_param4` <> 0;
DROP TABLE IF EXISTS `exploration_basexp`;
